spring.application.name=ResumeIQ
# Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/resumeiq_db
spring.datasource.username=root
spring.datasource.password=Kp28@pandey

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
